### ISSUE TITLE
Inconsistent handling of gradleWrapperMainVersion in prepare_cleanup.sh

### ISSUE THREAD

**Issue by yibo-long** [entur/gradle-orb#15]
Wanted to try out this orb as I was researching the improvements can be done with CircleCI's gradle caching handling, and thanks for making those great improvements!

Our repo is a monorepo, so we are also leveraging parameter `app_src_directory`, however the handling of gradleWrapperMainVersion doesn't seem to align between [prepare_cleanup.sh](https://github.com/entur/gradle-orb/blob/master/src/scripts/prepare_cleanup.sh#L24) and [cleanup.sh](https://github.com/entur/gradle-orb/blob/master/src/scripts/cleanup.sh#L31), and we got the following errors when trying out:

```
cat: services/foo-service/gradle/wrapper/gradle-wrapper.properties: No such file or directory
```

**Comment by yibo-long** [comment]
I realized we are setting us our monorepo a little different from what this orb is looking for. 

We only have one single gradle wrapper at the root of the monorepo, and have CircleCI to only build the gradle subproject with a split like `./gradlew :services:foo-service:build`.

**Comment by skjolber** [comment]
Is `with_cache` working better?

**Comment by yibo-long** [comment]
we are using `with_cache`, however with `with_cache`, it can only accept `deps_checksum_file` at the root of the directory by [find](https://github.com/entur/gradle-orb/blob/8e4df596ee6d467b593c51ef64292c905da914d0/src/scripts/checksum_build_files.sh#L21). I at first thought `app_src_directory` in `with_cache` is to address this difference, but it doesn't.

Our repo's setup requires the flow working somewhat under this way:
1. check build file cache from `./services/foo-service/build.gradle.kts`
2. check gradle cache from `./gradle/wrapper/gradle-wrapper.propertie`
3. run `./gradlew :services:foo-service:build` at root
4. save cache

**Comment by yibo-long** [comment]
Closing the issue as it's not really a relevant setup. Thanks for all cool inspirations!
